import { NextRequest, NextResponse } from "next/server";
import { requireAuth } from "@/lib/auth";
import { db } from "@/db";
import { jams, jamMembers, users } from "@/db/schema";
import { eq, and } from "drizzle-orm";
import { followPlaylist, updatePlaylistDetails } from "@/lib/spotify";
import { generateId, formatDigName, getFirstName } from "@/lib/utils";

// POST /api/jams/[jamId]/join — join via invite code
export async function POST(
  request: NextRequest,
  { params }: { params: Promise<{ jamId: string }> }
) {
  const user = await requireAuth();
  const { jamId } = await params;
  const body = await request.json();
  const { inviteCode } = body;

  const jam = await db.query.jams.findFirst({
    where: eq(jams.id, jamId),
    with: { members: { with: { user: true } } },
  });

  if (!jam) {
    return NextResponse.json({ error: "Jam not found" }, { status: 404 });
  }

  if (jam.inviteCode !== inviteCode) {
    return NextResponse.json({ error: "Invalid invite code" }, { status: 403 });
  }

  // Check if already a member
  const existing = jam.members.find((m) => m.user.id === user.id);
  if (existing) {
    return NextResponse.json({ error: "Already a member" }, { status: 400 });
  }

  // Add to members
  await db.insert(jamMembers).values({
    id: generateId(),
    jamId,
    userId: user.id,
  });

  // Follow the Spotify playlist
  await followPlaylist(user.id, jam.spotifyPlaylistId);

  // Update playlist name if it was auto-generated
  const allMembers = [...jam.members.map((m) => m.user), user];
  const memberFirstNames = allMembers.map((m) => getFirstName(m.displayName));
  const newName = formatDigName(memberFirstNames);

  // Only update name if user hasn't customized it
  const currentNameIsAutoGenerated =
    jam.name.endsWith("Deep Digs");
  if (currentNameIsAutoGenerated) {
    await updatePlaylistDetails(jam.ownerId, jam.spotifyPlaylistId, {
      name: newName,
    });
    await db.update(jams).set({ name: newName }).where(eq(jams.id, jamId));
  }

  return NextResponse.json({ success: true, jamId });
}
